### ISSUE TITLE
big ass tabs

### ISSUE THREAD

**Issue by MODKILLER1001** [maejok-xx/maejok-tools#16]
still fucked on 2.7.2
![image](https://github.com/maejok-xx/maejok-tools/assets/17520451/ccba4947-d242-40f3-9f07-a4c4fb74469b)
running 
Google Chrome | 120.0.6099.71 (Official Build) (64-bit) (cohort: Stable Installs & Version Pins)
Revision | 9729082fe6174c0a371fc66501f5efc5d69d3d2b-refs/branch-heads/6099_56@{#13}
OS | Windows 11 Version 22H2 (Build 22621.2715)
JavaScript | V8 12.0.267.8
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Tamper monkey 5.0

#11

**Comment by maejok-xx** [comment]
can you post a screenshot of the about page?
