### ISSUE TITLE
Total XP inventory counter

### ISSUE THREAD

**Issue by ichinchin** [maejok-xx/maejok-tools#17]
Add a counter that automatically calculates how much XP your inventory is worth
![image](https://github.com/maejok-xx/maejok-tools/assets/57413489/ab54c6b3-366f-45fc-b2cc-306d306b9f80)

**Comment by maejok-xx** [comment]
All the item XP values are stored server-side and are constantly changing.  I wouldn't be able to maintain accurate data on them.

However, this may be something I could add to the actual site...
