### ISSUE TITLE
Big chat bug

### ISSUE THREAD

**Issue by you1307** [maejok-xx/maejok-tools#2]
if you have persist big chat on, make chat big, and refreash. the next time you hit the poll button or the log button it minimizes again.

Vid: https://drive.google.com/file/d/1X8z2_vKQpmUGLRscBwRw_LeR9FpI42Q3/view?usp=drive_link

**Comment by maejok-xx** [comment]
> #4 created bigger bug... not clicking the tab buttons always switches you to big chat mode.

fixed by #8
