### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Tickle** [maejok-xx/maejok-tools#33]
Allow us to disable the line overlay that is covering the whole page. 
@-moz-document url-prefix("https://www.fishtank.live/") {
  body::after {
    content: none !important;
  }
}
Doing this in Stylus does the trick.

Also adding the https://pastebin.com/raw/gVz5Ys4w console script to add faster navigation would be great

**Comment by maejok-xx** [comment]
The sidebar livestream navigation is a good idea.  Might actually be something worth adding to the actual site though, instead of the plugin.  If I can't add something like that to the site, I'll add it to the plugin.

Thanks for the suggestions!

**Comment by Tickle** [comment]
Sounds good, if I can make a last request it is to make it so that the sound levels apply every time you switch camera, because at the moment it goes back to max volume and you need to touch the sound slider and move it one pixel over so that it reapplies the sound after you switch

**Comment by barrettotte** [comment]
> The sidebar livestream navigation is a good idea. Might actually be something worth adding to the actual site though, instead of the plugin. If I can't add something like that to the site, I'll add it to the plugin.
> 
> Thanks for the suggestions!

For what its worth, I threw this together in the meantime. Its a little hacky, but seems to get the job done - https://github.com/barrettotte/fishtank-s02-qol
