### ISSUE TITLE
REQUEST: Wartoy logging

### ISSUE THREAD

**Issue by HQv2** [maejok-xx/maejok-tools#41]
Is there any possibility of logging clan attacks/wartoys used? It's unfortunate that you could get attacked and there is no way of knowing who did it unless you catch the small message in the chat. Thank you!

**Comment by maejok-xx** [comment]
This is more of a site feature that should be added rather than plugin feature, but I'll definitely see about adding it to the site.  If for whatever reason I can't add to the site (can't imagine why not) then I'll add to the plugin.

**Comment by HQv2** [comment]
> This is more of a site feature that should be added rather than plugin feature, but I'll definitely see about adding it to the site. If for whatever reason I can't add to the site (can't imagine why not) then I'll add to the plugin.

Appreciate you, man. If I only knew who attacked, I would buy wartoys, so it would be a good business decision.

**Comment by maejok-xx** [comment]
Closing this since wartoy logging is now a native Fishtank feature! 🥲
