### ISSUE TITLE
Bounds check needed for 'Enter Clan Chat Automatically' option

### ISSUE THREAD

**Issue by dennislv** [maejok-xx/maejok-tools#48]
Non-members who enable the 'Enter Clan Chat Automatically' option by accident, or intentional, will experience a crash.  

userscript.html?name=MAEJOK-TOOLS-for-Fishtank.live.user.js&id=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx:22 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'tag')
    at Se (userscript.html?name=MAEJOK-TOOLS-for-Fishtank.live.user.js&id=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx:22:101578)

![image](https://github.com/maejok-xx/maejok-tools/assets/4878314/348fa047-abbd-4622-aefc-68532214ff8f)

![image](https://github.com/maejok-xx/maejok-tools/assets/4878314/0f05968c-90b8-486e-a937-f477357372fe)

_I redacted the uuid in case its usable (?) to someone else._

**Comment by maejok-xx** [comment]
Thank you! This is caused by the latest update. Will push a fix tonight.
